# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_assigned', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('units', models.IntegerField(default=3)),
                ('description', models.TextField()),
                ('is_current_sem', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expertise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_years', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course')),
            ],
        ),
        migrations.CreateModel(
            name='PrevAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2015)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('LEC', 'Lecture'), ('TUT', 'Tutorial'), ('PRA', 'Practical')], max_length=3)),
                ('display_text', models.CharField(max_length=50)),
                ('num_hours', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('ADM', 'Admin'), ('HOD', 'Head Of Department'), ('FAC', 'Faculty')], max_length=3)),
                ('password', models.CharField(max_length=100)),
                ('applied_sections', models.ManyToManyField(through='dashboard.Application', to='dashboard.Section')),
                ('expert_courses', models.ManyToManyField(related_name='experts', through='dashboard.Expertise', to='dashboard.Course')),
                ('prev_assigned_courses', models.ManyToManyField(related_name='prev_assignees', through='dashboard.PrevAssignment', to='dashboard.Course')),
            ],
        ),
        migrations.AddField(
            model_name='prevassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.User'),
        ),
        migrations.AddField(
            model_name='expertise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.User'),
        ),
        migrations.AddField(
            model_name='application',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Section'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.User'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('course', 'display_text')]),
        ),
        migrations.AlterUniqueTogether(
            name='prevassignment',
            unique_together=set([('user', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='expertise',
            unique_together=set([('user', 'course')]),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('user', 'section')]),
        ),
    ]
