# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_course_course_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='applied_sections',
        ),
        migrations.RemoveField(
            model_name='user',
            name='expert_courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prev_assigned_courses',
        ),
        migrations.AddField(
            model_name='course',
            name='experts',
            field=models.ManyToManyField(related_name='expert_courses', through='dashboard.Expertise', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='prev_assignees',
            field=models.ManyToManyField(related_name='prev_assigned_courses', through='dashboard.PrevAssignment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='applied_users',
            field=models.ManyToManyField(through='dashboard.Application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prevassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
