# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160218_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timewindow',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='timewindow',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
