# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 06:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20160220_0557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': (('assign_application', 'Can assign or approve the application'),)},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('course_name',)},
        ),
        migrations.AlterField(
            model_name='section',
            name='applied_users',
            field=models.ManyToManyField(related_name='applied_sections', through='dashboard.Application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='section',
            name='num_hours',
            field=models.IntegerField(default=3),
        ),
    ]
